name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and push Docker image to AWS ECR
      - name: Build and push Docker image
        env:
          IMAGE_REPO_NAME: loanify-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create the ECR repository if it doesn't exist
          aws ecr create-repository --repository-name $IMAGE_REPO_NAME || true
          
          # Build and tag the Docker image
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          
          # Push the image to ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials (again for the deploy job since it didn't have configure credentials)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Configure AWS credentials and check if the S3 bucket exists to store terraform state
      - name: Ensure Terraform backend S3 bucket exists
        run: |
          aws s3api head-bucket --bucket loanify-terraform-state-bucket || \
          aws s3api create-bucket --bucket loanify-terraform-state-bucket --region ${{ env.AWS_REGION }}

      # Step 5: Lint Terraform code
      - name: Run TFLint
        run: |
          curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.46.1/tflint_linux_amd64.zip
          unzip tflint.zip -d /usr/local/bin/
          tflint --version
          tflint --init
          tflint

      # Step 6: Run tfsec for security analysis
      # - name: Run tfsec
      #   run: |
      #     curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64
      #     chmod +x tfsec
      #     mv tfsec /usr/local/bin/
      #     tfsec --version
      #     tfsec .

      # Step 7: Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Step 8: Validate Terraform code
      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      # Step 9: Plan Terraform changes
      - name: Terraform Plan
        env:
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
        run: |
            cd terraform
            terraform plan

      # Step 8: Apply Terraform changes
      - name: Terraform Apply
        run: |
            cd terraform
            terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
